### ISSUE TITLE
Use lumberjack for more logging features

### ISSUE THREAD

**Issue by chrislee87** [liftbridge-io/liftbridge#1]
[lumberjack](https://github.com/natefinch/lumberjack) can be used with logrus, it can add more features for logging, such as log retention by message age, log retention by number of messages, log compaction.

**Comment by chrislee87** [comment]
Code snippet as below would work:
`logger.Out = &lumberjack.Logger{
		Filename:   conf.LogFilename,
		MaxSize:    conf.LogMaxSize,
		MaxBackups: conf.LogMaxBackups,
		MaxAge:     conf.LogMaxAge,
		LocalTime:  conf.LogLocalTime,
		Compress:   conf.LogCompress,
	}`

**Comment by tylertreat** [comment]
Hi, if you'd like to put together a PR I'd be happy to take a look.

**Comment by justinfx** [comment]
If this gets added, it would be good to leave log management turned off by default, since log rototation for a service seems like the responsibility of a process manager when managing stdout/stderr

**Comment by tylertreat** [comment]
Agreed, log files should be off by default.

**Comment by tylertreat** [comment]
The current PR for this is [here](https://github.com/liftbridge-io/liftbridge/pull/4) btw.

Thinking about this more, I'm trying to decide if adding these kinds of logging features is really appropriate to have in the system or not. I tend to agree with @justinfx in that it's better to log to stdout/stderr and have something pick that up, such as Logstash or Fluentd. I'm also not sure how I feel about coding the API to a specific implementation (Lumberjack in this case).

**Comment by ppizarro** [comment]
As suggested in the [Let's talk about logging](https://dave.cheney.net/2015/11/05/lets-talk-about-logging), we could simplify the logging interface to:

```
type Logger interface {
	Debugf(string, ...interface{})
	Infof(string, ...interface{})
	Debug(...interface{})
	Info(...interface{})
}
```

I think we could implement this interface using [log](https://golang.org/pkg/log) package from Go rather than using a third-party library. In this implementation we would have a method to EnableDebug and create a flag in main to enable debug mode.

**Comment by tylertreat** [comment]
Closing this for now as there is no work planned for this.
