### ISSUE TITLE
Implement better documentation system

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#100]
Migrate [documentation](https://github.com/liftbridge-io/liftbridge/tree/master/documentation) to a proper docs system, such as MkDocs or Docusaurus.

**Comment by sevein** [comment]
@tylertreat, one option could be hugo + [docsy.dev](docsy).

**Comment by tylertreat** [comment]
Thanks @sevein. I'm currently in the process of migrating docs to [Docusaurus](https://docusaurus.io/). New website with docs should be up later this week!

**Comment by sevein** [comment]
That's awesome! Thanks.

**Comment by tylertreat** [comment]
New docs/website are live at https://liftbridge.io.

**Comment by sevein** [comment]
Congrats, looking great!
