### ISSUE TITLE
Acknowledgement delay when follower idle

### ISSUE THREAD

**Issue by paddybyers** [liftbridge-io/liftbridge#102]
We're seeing quite a significant latency impact awaiting acknowledgements when replication > 1 due to https://github.com/liftbridge-io/liftbridge/blob/f3ae7279bf750e5b5ca9557d91187fc2f355e541/server/partition.go#L760.

Do you have any thoughts about how you might address this?

**Comment by tylertreat** [comment]
Yes, this is a big annoyance of mine that I'd like to get fixed. Ultimately, the intention of the sleep is to prevent idle followers from just _hammering_ leaders with replication requests, but as the TODO mentions, it's a rather naive solution.

I have a few thoughts on improving this. One thought is potentially replacing the use of NATS for internal replication with a bidirectional gRPC stream. The leader would just push messages to the follower, and the follower would periodically "check in" with the leader. Another thought is to implement some kind of long-polling mechanism on top of NATS.

I need to look at what Kafka does to avoid this issue since I believe its replication works in a very similar fashion (i.e. synchronous request/response replication RPCs).

Also, I'm completely open to suggestions if you have any solutions in mind.

@paddybyers Out of curiosity, is this an issue for you due to not having sustained load going through Liftbridge such that you're repeatedly hitting this added latency? And the added latency should be capped at ~1s. Is that roughly what you're experiencing?

**Comment by paddybyers** [comment]
> Out of curiosity, is this an issue for you due to not having sustained load going through Liftbridge such that you're repeatedly hitting this added latency? And the added latency should be capped at ~1s. Is that roughly what you're experiencing?

We've been benchmarking a range of different workloads, but a relatively common case is a stream that that has a low message rate - say 1Hz - and then the time taken to acknowledge is usually ~200ms (just because the follower ends up waiting roughly 4 * 300ms). Acknowledgement delays in the region 100-300ms are problematic for our use-case, because we can't do any onward processing of an event before it has been committed in multiple locations.

I haven't thought much about how to address it, but it seems to me that the long polling idea might have some legs. The leader knows, when it sends a response indicating that there are no further messages, that the follower will then become idle. So the leader already knows that it would have to do something proactive on the next message in order to get the follower to wake up and handle it. Knowing that, could there be multiple replies if the first response from the leader indicates that there are no further messages - ie there will be a subsequent reply to the follower once the next message needs to be handled.

**Comment by tylertreat** [comment]
> Knowing that, could there be multiple replies if the first response from the leader indicates that there are no further messages - ie there will be a subsequent reply to the follower once the next message needs to be handled.

Yeah, this makes sense and is probably the approach to take. The only nuance is around health checking of the leader, i.e. followers rely on their regular polls to ensure the leader hasn't died. But I think this can/should be solved by having a separate, less frequent health check loop.

**Comment by tylertreat** [comment]
FYI I'm looking at this issue now. Hopefully will have a fix sometime this week.

**Comment by paddybyers** [comment]
> FYI I'm looking at this issue now. Hopefully will have a fix sometime this week.

Great, thanks. What approach are you taking?

**Comment by tylertreat** [comment]
Starting with a "long poll" approach and we'll see how that works. I'll likely ask if you can test out the fix before committing to master if you're able/willing to.

**Comment by paddybyers** [comment]
> I'll likely ask if you can test out the fix before committing to master if you're able/willing to.

Of course, yes, thanks

**Comment by paddybyers** [comment]
> The only nuance is around health checking of the leader, i.e. followers rely on their regular polls to ensure the leader hasn't died. But I think this can/should be solved by having a separate, less frequent health check loop.

Just on this point: I think the frequency of the polling for the purposes of health checking can be reduced, down to something derived from the configured limit (`ReplicaMaxLeaderTimeout` or `ReplicaMaxLagTime` or whatever) - but are you planning still to use the same request/response cycle for those health checks? I'm thinking that if you create some other request/response cycle for the health check, then you risk a situation in which this replication loop is stalled for some reason, but the leader is appearing to be healthy in other respects.

**Comment by tylertreat** [comment]
I am planning to use the same request/response cycle for health checks but reduce the frequency as you suggested. Here is what I've implemented and will be testing out shortly:

1. Follower makes request to leader to replicate messages
2. Leader sends back replication response with messages as normal
3. Follower stores replicated messages and is now caught up with leader
4. Follower makes subsequent replication request to leader with offset == leader's log end offset
5. Leader notes follower is caught up, registers a data waiter on the log, and sends back empty replication response containing the HW
6. Follower notes it is caught up and sleeps for some duration `s`

At this point, one of two outcomes happen:
1. More messages are written to the leader's log. In this case, the registered waiter is notified which in turn sends a notification to the follower to preempt the sleep. The follower then begins fetching data as usual.
2. The follower sleeps the full duration `s`, wakes up, and begins fetching data as usual. If there is still no data, the process repeats itself. The primary purpose of `s` is to ensure timely health checks of the leader still happen. `s` can be much higher than the 1 second max sleep today, perhaps 5-10 seconds with some random jitter or something derived from `ReplicaMaxLeaderTimeout` as you suggest?

**Comment by tylertreat** [comment]
@paddybyers [This branch](https://github.com/liftbridge-io/liftbridge/tree/fix_idle_follower_lag) implements the strategy described above. Could you try it out and see how it works for you?

**Comment by paddybyers** [comment]
> Could you try it out and see how it works for you?

That's great, thanks. We'll try it tomorrow.

**Comment by paddybyers** [comment]
We've been running some tests and the initial impression is that this does fully solve the acknowledgement delay. We will be able to post additional results once we've run some more tests, but so far this looks good. Thanks for doing this.

**Comment by tylertreat** [comment]
Great to hear. I have one last tweak I'm going to make to it. Looking forward to your test results and hopefully can get it merged in soon.

**Comment by tylertreat** [comment]
Closing this since it was resolved in #107.
