### ISSUE TITLE
Feature matrix

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#104]
Make a feature matrix comparing Liftbridge with similar systems to help people understand the differences. This should live in the documentation website.

**Comment by alexisread** [comment]
I haven't found any comparisons of NATS to MQTT, a quick explanation of NATS advantages over MQTT re: suitability for Liftbridge would be really helpful as I'm considering a fork to use MQTT instead of NATS.

(broker scaleout with Emitter.io seems similar in capability)
Thanks

**Comment by tylertreat** [comment]
Include Jetstream as part of this (see #145).

**Comment by rafsawicki** [comment]
@tylertreat  #145 that asked for feature comparison with Jetstream was closed as being tracked by this issue. I don't see Jetstream mentioned in #191 which closes this issue , did you decide to not add it at all?

**Comment by rafsawicki** [comment]
I've read into all responses in #145 and noticed that you're planning to add it to comparison once the stabilize the API. This basically answers my own question, so feel free to ignore it :) .

**Comment by tylertreat** [comment]
@rafsawicki Yep, I'll add it once there is a stable release.

**Comment by tipiirai** [comment]
Would love to see Jetstream on the [feature comparison](https://liftbridge.io/docs/feature-comparison.html). Thanks!

**Comment by Just4Ease** [comment]
Hi @tipiirai :)  Any update on jetstream comparison yet?

**Comment by losinggeneration** [comment]
As a note, JetStream went [generally available](https://github.com/nats-io/jetstream/blob/master/README.md) in [NATS 2.2.0](https://github.com/nats-io/nats-server/releases/tag/v2.2.0) released on 2021/03/14
