### ISSUE TITLE
Connect to NATS cluster with username/password

### ISSUE THREAD

**Issue by PieterScheffers** [liftbridge-io/liftbridge#108]
In the [documentation of NATS server](https://nats-io.github.io/docs/developer/security/userpass.html#connecting-with-a-userpassword-in-the-url) I found that you can connect to a NATS server with the Go NATS client with a username and password in the url. When I use a username and password in the NATS server url for Liftbridge I get the following message:
```
panic: failed to connect to NATS: parse nats://myuser:mypassword: invalid port ":mypassword" after host
```
(I have changed the username and password with placeholders, the actual password has a special character in it (`^`))

Should I connect in some other way to use a username/password for the NATS cluster, or is this not possible yet?

**Comment by tylertreat** [comment]
This sounds like a bug. I will take a look...

**Comment by tylertreat** [comment]
I have not been able to reproduce either through config file or CLI flag, though I think special characters are invalid in the username/password possibly?

```
parse nats://a:b^@localhost:4222: net/url: invalid userinfo
```

The following test worked however:

```
nats://a:b@localhost:4222
```

Can you show the full connection string you're using (with username/password masked)?

**Comment by PieterScheffers** [comment]
My Liftbridge config look like this:
```
          listen: 0.0.0.0:9292
          data.dir: /liftbridge-data
          log.level: debug

          # Define NATS cluster to connect to.
          nats {
              servers: ["nats://admin:Fc5^mW7d1kw1LbHh1^#dZk@nats-cluster:4222"]
          }

          # Specify message log settings.
          # Keep all messages
          log {
              retention.max.age: "0"
          }

          # Specify cluster settings.
          clustering {
              server.id: "liftbridge-0"
              namespace: "liftbridge"
              raft.bootstrap.peers: [ "liftbridge-0", "liftbridge-1", "liftbridge-2" ]
          }
```

**Comment by tylertreat** [comment]
Okay, I see the issue now. With special characters in username/password it looks like the NATS client requires using [`UserInfo`](https://godoc.org/github.com/nats-io/go-nats#UserInfo). I will work on a fix.

**Comment by tylertreat** [comment]
This has been resolved in https://github.com/liftbridge-io/liftbridge/pull/112. To set the NATS user/password, add the following to your Liftbridge config file:

```
 # Define NATS cluster to connect to.
nats {
    servers: ["nats://nats-cluster:4222"]
    user: "admin"
    password: "Fc5^mW7d1kw1LbHh1^#dZk"
}
```

**Comment by PieterScheffers** [comment]
Thank you!
