### ISSUE TITLE
Latest offset in stream metadata

### ISSUE THREAD

**Issue by bruth** [liftbridge-io/liftbridge#111]
I am not sure how costly this would be to maintain in practice, but the use case is to support single producer streams to know when the end-of-stream has been reached.

There is a way to emulate this which relies on a timeout on the latency of a message being received. Assuming some p99.x of this latency is stable, then this addition may not be necessary.

**Comment by tylertreat** [comment]
Yeah I think it makes sense to expose latest offset or at least the high watermark. For example, probably need it for this: https://github.com/liftbridge-io/liftbridge/issues/54

Need to think through implementation.

**Comment by tylertreat** [comment]
Addressed in #265
