### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by sammy007** [liftbridge-io/liftbridge#137]
I fired up 2 servers on the same machine:

N1
```
liftbridge --raft-bootstrap-seed
```

N2

```
liftbridge --data-dir /tmp/liftbridge/server-2 --port=9293
```

Wrote 500K items and I see that only 1st data dir increasing in size. The datadir of 2nd server is intact. I expected both servers to contain a copy of each other's data.

What is wrong with setup or understanding the idea behind this project?

**Comment by tylertreat** [comment]
The default replication factor is 1 if not set. When creating the stream, you either need to set it to 2 (number of servers you have) or -1 (which sets the replication factor to the size of the cluster, i.e. 2 in your case).

**Comment by sammy007** [comment]
Just noticed, thank you. I set it to -1 and all seems fine until I fire up another server. After I have added 3rd server new data (and existing data from 2 nodes) never goes to its data dir.

**Comment by tylertreat** [comment]
The replication factor is fixed once the stream is created. Thus if a new
server is started after stream creation, it won't be replicated to.

**Comment by tylertreat** [comment]
Closing this, but let me know if you still have questions.
