### ISSUE TITLE
Server crash when subject is not provided on CreateStream

### ISSUE THREAD

**Issue by caioaao** [liftbridge-io/liftbridge#140]
To reproduce:
1. Run 

````
docker run -d -p 4222:4222 -p 9292:9292 -p 8222:8222 -p 6222:6222 liftbridge/liftbridge-docker
````

2. Call "create stream" method passing only stream name.

The server outputs this and then crashes:
```
time="2019-12-23 00:03:59" level=error msg="Server failed becoming leader for partition [subject=, stream=chyRtFVDds, partition=0]: failed to subscribe to NATS: nats: invalid subject"
panic: failed to add partition to metadata store: failed to subscribe to NATS: nats: invalid subject
```

**Comment by tylertreat** [comment]
Can you explain the reproduce steps in more detail? `Subscribe` doesn't take a subject argument. Does this happen after creating a stream without a subject?

**Comment by caioaao** [comment]
Sorry. I wrote the wrong method. This happens on `CreateStream`.
