### ISSUE TITLE
Jet stream versus liftbridge

### ISSUE THREAD

**Issue by joeblew99** [liftbridge-io/liftbridge#145]
So NATS has started to release Jetstream.

Interesting times as they say.

So I would really appreciate a comparison wiki article 

Right now we are in the middle of picking  a framework.

Liftbridge is nice in that is provides a grpc interface.

But the main thing we need is a global mesh where you just add more servers to give HA / throughput. Self healing too.

Liftbridge depends on NATS and not NATS streaming and Jetstream NATS apparently will depends on NATS and not need NATS Streaming I read. Right now Jetstream NATS only has file durability.

So interesting decision matrix architecturally.

If Jetstream NATS gets ha replication everyone is happy. Liftbridge can switch to use the Jetstream API and users get the benefit of simplified grpc queues like now.

So I would love to see roadmap / design trade off thoughts from anyone that has thoughts on this matter 

.

**Comment by tylertreat** [comment]
I'm planning to do a [feature matrix](https://github.com/liftbridge-io/liftbridge/issues/104) that will probably include Liftbridge, Kafka, Pulsar, and NATS Streaming initially. Will definitely include Jetstream once it matures. Right now, it seems like the feature set and APIs are rapidly evolving. Once there's a stable product, we can see how it compares.

**Comment by tylertreat** [comment]
Closing this issue since it is being tracked in #104. Please refer there.
