### ISSUE TITLE
Docker images not pushed with tag version

### ISSUE THREAD

**Issue by caioaao** [liftbridge-io/liftbridge#161]
Probably due to this: https://discuss.circleci.com/t/workflows-with-jobs-triggered-by-tag/18543
Jobs are not being run for tags, only commits

**Comment by tylertreat** [comment]
I believe this is because we are not specifying a tag filter here: https://github.com/liftbridge-io/liftbridge/blob/3683ddf64c2c13bb690a0f32a460b2d85e29dabf/.circleci/config.yml#L104-L106

**Comment by tylertreat** [comment]
This has been fixed.
