### ISSUE TITLE
Stream creation deadline when no metadata leader

### ISSUE THREAD

**Issue by Jmgr** [liftbridge-io/liftbridge#163]
Creating a stream when no metadata/Raft leader has been elected results in a "No known metadata leader" error being returned.

Could it be possible to implement a behavior similar to what happens when `Publish` is called, where the API call would return a result (either success or failure) after some time if a context with a deadline has been provided?

**Comment by tylertreat** [comment]
Are you seeing this in an actual deployment or just in Liftbridge tests? I've noticed an elevated number of these errors in the tests and think it might be related to updating the version of Raft.

**Comment by tylertreat** [comment]
Agree it should be more resilient though.

**Comment by tylertreat** [comment]
Indeed, it looks like updating the Raft version has surfaced a race condition. I think you are right, the best solution is to probably rely on a context deadline to wait for leadership to be established.
