### ISSUE TITLE
Raft events order same as activity stream order?

### ISSUE THREAD

**Issue by Jmgr** [liftbridge-io/liftbridge#179]
Regarding the activity stream: is the order of the Raft events (for instance partition created, stream deleted) guaranteed to be the same within the activity stream? In other words, is it theoretically possible (but probably unlikely) to end up with a stream deletion event being stored before the partition creation (triggering the stream creation) in the activity stream?

**Comment by tylertreat** [comment]
> is it theoretically possible (but probably unlikely) to end up with a stream deletion event being stored before the partition creation (triggering the stream creation) in the activity stream?

Currently, yes. Solving this will also be a goal of the work to address #177.

**Comment by tylertreat** [comment]
I am beginning to take a look at this today.

**Comment by Jmgr** [comment]
Great, thank you.
