### ISSUE TITLE
Embed NATS

### ISSUE THREAD

**Issue by ghost** [liftbridge-io/liftbridge#19]
I was wondering if we can support NATS embedding ? This is when you import the NATS server into your own server.

For my uses case I intend to  run lift bridge on desktops.

**Comment by tylertreat** [comment]
Yes, supporting an embedded mode is planned.

**Comment by gedw99** [comment]
Ok. If I get time I will take a crack at it. I believe it's quite easy to
do embedding with NATS.

**Comment by tylertreat** [comment]
Yeah, the key thing is how we expose configuration for the embedded NATS instance.

**Comment by gedw99** [comment]
I am guessing you want to allow it the run embedded and not embedded ?

**Comment by tylertreat** [comment]
Right, it should support both.

**Comment by gedw99** [comment]
Ok then.
So maybe master config should have a Boolean for embedded.
If it is true then the rest of the config ( which is optional ) has the
NATS config.

If it's not true it just does not bother reading the NATS data required to
embed a NATS server.

---

This leads to the question of discovery doesn't it. Any decent system must
be HA and so you want to make it easy to bring up a node and have it join.
NATS needs consul to bootstrap in this HA scenario I presume.
In which case the config is from consul ( or etcd ). If this assertion is
true then maybe it's better to design embedding to work with consul ?

Or just go for non consul solution initially ?

I defer to your experience Tyler on this one..

**Comment by tylertreat** [comment]
I would prefer to keep it agnostic of any service discovery implementations (Consul, etcd, etc.). If anything, I think that should be handled external to the Liftbridge code, e.g. with config templating (down the road we'll likely need to support config reload). NATS nodes are designed to be mostly "self-discovering", you just need to point to a seed node. Liftbridge clustering is designed similarly.

To start, I think we should just keep it simple and probably model it off of [what NATS Streaming does](https://github.com/nats-io/nats-streaming-server#configuring).

**Comment by gedw99** [comment]
Ok well that clears up the scope unless there is anything else.

What did you mean in reference to NATS Streaming ?
- the way it embeds NATS or the way is does service discovery ?

**Comment by tylertreat** [comment]
The way it embeds NATS. We can probably do similar.

**Comment by benrogmans** [comment]
What's your current take on embedding NATS?

Ref: https://github.com/liftbridge-io/liftbridge/issues/53#issuecomment-462437915

**Comment by tylertreat** [comment]
The current plan is still to provide an option to run Liftbridge with an embedded NATS server. For config, my current thinking is to just have an option that allows pointing to a NATS config file rather than trying to embed NATS config within Liftbridge's config.
