### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#196]
The `TestCreateStreamNoMetadataLeader` unit test fails occasionally and should be fixed.

**Comment by LaPetiteSouris** [comment]
> The `TestCreateStreamNoMetadataLeader` unit test fails occasionally and should be fixed.

on it

**Comment by LaPetiteSouris** [comment]
I have an example of the error thrown on CI, but unable to reproduce locally

https://circleci.com/gh/liftbridge-io/liftbridge/780

Anyone has seen this test failing locally ?

**Comment by vcabbage** [comment]
At a glance, it seems likely to be a race on removing `storagePath`. https://github.com/liftbridge-io/liftbridge/blob/84b27dd0daa5b38485361e3217317ee2cb1834f3/server/server_test.go#L24-L40

Moving the cleanup from the individual tests into a [`TestMain`](https://golang.org/pkg/testing/#hdr-Main) would be a relatively simple way to make it more robust.

**Comment by tylertreat** [comment]
```
panic: failed to checkpoint high watermark: cannot create temp file: open /tmp/liftbridge_test_103530399/b/streams/foo/0/replication-offset-checkpoint862222957: no such file or directory
```

I believe this particular error is due to removing `storagePath`.

Though the actual error I was referring to is this one [here](https://circleci.com/gh/liftbridge-io/liftbridge/1007).

```
--- FAIL: TestCreateStreamNoMetadataLeader (7.49s)
    api_test.go:129: 
        	Error Trace:	api_test.go:129
        	Error:      	Not equal: 
        	            	expected: "no known metadata leader"
        	            	actual  : "context deadline exceeded"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-no known metadata leader
        	            	+context deadline exceeded
        	Test:       	TestCreateStreamNoMetadataLeader
```

I think I know what the issue is. Will take a look.
