### ISSUE TITLE
arm binaries

### ISSUE THREAD

**Issue by c-nv-s** [liftbridge-io/liftbridge#202]
is it possible to include arm7 and arm64 binaries along with the releases please

**Comment by tylertreat** [comment]
The reason the initial release didn't include arm binaries is because the [mmap library](https://github.com/nsip/gommap) Liftbridge currently relies on doesn't support arm. This needs to be addressed before we can build on arm.

**Comment by mmickan** [comment]
It looks like this was addressed in nsip/gommap in December 2020.

**Comment by tylertreat** [comment]
ARM is now supported on MacOS, Linux, and Windows. Binaries are available for MacOS and Windows as of v1.7.1. The ARM binary for Linux will be available in the next release.
