### ISSUE TITLE
Tag next release

### ISSUE THREAD

**Issue by AnatolyRugalev** [liftbridge-io/liftbridge#203]
Hi!

We'd like to try liftbridge in our project and we have to build liftbridge from master now because there was no release since d9fc5f12f466d39e4e332bc8fb13e05c240444e0.

Could you please tag a 1.0.1 version? If not, can you tell when next release will happen?

Thank you for your efforts

**Comment by tylertreat** [comment]
Yes, I'll be tagging the next release shortly.

**Comment by tylertreat** [comment]
[v1.1.0](https://github.com/liftbridge-io/liftbridge/releases/tag/v1.1.0) is now available.
