### ISSUE TITLE
Dockerfile.k8s still has bzr

### ISSUE THREAD

**Issue by neil-pozetroninc** [liftbridge-io/liftbridge#207]
As part of our effort to provide a community developed [Helm chart](https://github.com/pozetroninc/liftbridge-helm-chart) we currently build the [k8s Docker image](https://hub.docker.com/r/pozetroninc/liftbridge) automatically. 

Since bzr is no longer available in Alpine Linux as of 3.12 (alpinelinux/docker-alpine#87) these no longer build. The fix is the same as was done for the standalone Dockerfile.

Thanks for the awesome software and we hope that the Helm chart can help someone!

**Comment by tylertreat** [comment]
Awesome to see the Helm chart, wasn't even aware! Will get the k8s Dockerfile fixed up.
