### ISSUE TITLE
CRDT based Nats on a Log. Idea / Discussion

### ISSUE THREAD

**Issue by joe-getcouragenow** [liftbridge-io/liftbridge#212]
If i wanted to have 20 CDN instances of NATS and liftbridge, then a CRDT based nats on a log would be an interesting proposition.

Here is a good example.
https://github.com/StreamSpace/ants-db
See the Test:https://github.com/StreamSpace/ants-db/blob/master/antsdb_test.go

The CRDT based NATS would allow you to run hundreds of them, in a fault tolerant way, such that all would recover to the same state.
Interestingly, the above CRDT implementation allows storing messages and blobs ( images ). Its just IPFS Lite under the hood.
So it would also allow Liftbridge to support images, in that an image could save "new image" or "changed image" also, pointing back to the IPFS node(s). 

I am well aware this is really on the edge of what LiftBridge project is about, but i thought its worth throwing it out there.

Wondering about the implication in terms of linearizability with Liftbridge. The way the data is replicated from Nats on a log to the LIftbridge nodes might be easier using a CRDT based nats on a log ?

Happy to discuss / explore this with others if anyone wants to discuss ...

**Comment by tylertreat** [comment]
I'm not sure if I totally track what you're proposing. Since Liftbridge is an immutable data stream, I'm not sure I see how CRDTs apply? Though you could certainly implement CRDTs _on top_ of a Liftbridge stream.

Also keep in mind that nats-on-a-log/raft are only used to replicate cluster _metadata_ in Liftbridge (streams, partitions, partition leadership, etc.). Data replication is done through special consumers of the data streams.

**Comment by joe-getcouragenow** [comment]
> I'm not sure if I totally track what you're proposing. Since Liftbridge is an immutable data stream, I'm not sure I see how CRDTs apply? Though you could certainly implement CRDTs _on top_ of a Liftbridge stream.

Understood.

> 
> Also keep in mind that nats-on-a-log/raft are only used to replicate cluster _metadata_ in Liftbridge (streams, partitions, partition leadership, etc.). Data replication is done through special consumers of the data streams.

But the data hits NATS on a log first when a publication happens right ?

**Comment by tylertreat** [comment]
> But the mutation from a client hits nats-on-a-log first when a publication happens right ? Hence why i was wanting to use CRDT backing for it..

No, this is not the case. Client publishes do not go through nats-on-a-log/raft. [Here](https://liftbridge.io/docs/replication-protocol.html) is the replication protocol used for client publishes.

**Comment by joe-getcouragenow** [comment]
> > But the mutation from a client hits nats-on-a-log first when a publication happens right ? Hence why i was wanting to use CRDT backing for it..
> 
> No, this is not the case. Client publishes do not go through nats-on-a-log/raft. [Here](https://liftbridge.io/docs/replication-protocol.html) is the replication protocol used for client publishes.

Thank you for explaining this.  This really helps me understand the architecture. 
Hence, this Issue no longer make any sense, since nats-on-a-log is in the control plane and is not in the data plane.  

Will close :)
