### ISSUE TITLE
Allow advertised host override via environment variable for dev-standalone and possibly other images.

### ISSUE THREAD

**Issue by ruseinov** [liftbridge-io/liftbridge#246]
That would be very convenient for local testing and I’f bet for other scenarios too.

**Comment by tylertreat** [comment]
Agreed. If you're interested in contributing, I believe this is a matter of changing the [standalone image](https://github.com/liftbridge-io/liftbridge/tree/master/docker/dev-standalone) to use a config file with default values. Then values that are specified in a config file can be overridden via environment variables. [This](https://github.com/liftbridge-io/liftbridge/blob/master/docker/dev-standalone/script_runner.sh#L12) is where the Liftbridge process is started.

**Comment by ruseinov** [comment]
I am. Yes, I figured that I'd need to introduce default config to the container in order for that to work. I'll take a look.

**Comment by ruseinov** [comment]
There's an issue with that:
```
./script_runner.sh: set: line 4: can't access tty; job control turned off
[8] 2020/08/19 06:08:49.469671 [INF] Starting nats-server version 2.1.7
[8] 2020/08/19 06:08:49.469706 [INF] Git commit [not set]
[8] 2020/08/19 06:08:49.469966 [INF] Starting http monitor on 0.0.0.0:8222
[8] 2020/08/19 06:08:49.470018 [INF] Listening for client connections on 0.0.0.0:4222
[8] 2020/08/19 06:08:49.470023 [INF] Server id is NDWTJXHEX3NCGIPUAOWBORIAZFDDM5SOSUBMACMVYWEKCPSGOLT5G3XA
[8] 2020/08/19 06:08:49.470024 [INF] Server is ready
[8] 2020/08/19 06:08:49.470242 [INF] Listening for route connections on 0.0.0.0:6222
waiting nats server
time="2020-08-19 06:08:50" level=info msg="Shutting down..."
panic: failed starting listener: listen tcp: lookup registry on 10.0.2.3:53: no such host

goroutine 1 [running]:
main.main()
	/Users/romanuseinov/projects/go/liftbridge/main.go:25 +0x1bc
./script_runner.sh: fg: line 14: job %1 not created under job control
```

In order for this to work it needs to stop looking up the advertised host, because in our case it would be an `etc/hosts` alias to docker host. I guess we could either introduce a flag for that or prevent it from looking up by default, because my guess is it should be poking at `listen` address and leave the `host` alone.
