### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by Jmgr** [liftbridge-io/liftbridge#249]
Liftbridge offers a comprehensive and easy to use API, but does not bundle any command line tool at the moment. A Liftbridge CLI could be used in various contexts:

- performance evaluation: it could be used to benchmark a particular setup of Liftbridge servers, create streams, publish to them using various parameters and measure time, memory, CPU, and other parameters ;
- maintenance: some setups could imply a routine removal of streams in response to a particular event ;
- statistics gathering: creating a program using the Liftbridge client API may not always convenient, so it could be useful to get some information like the number of active streams from a command line utility (the tool would then output the data using a well-known format).

We have already implemented a simple tool internally in Go and could contribute it as a PR if there is interest for it.

**Comment by Jmgr** [comment]
Great! We should be able to create a PR soon.

> I think it ought to live in a separate repo?

I think that would make sense, yes. Do you want to create this repo first, and then we can submit a pull request on it?

**Comment by tylertreat** [comment]
I created a new repo here: https://github.com/liftbridge-io/liftbridge-cli

**Comment by Jmgr** [comment]
Thanks. I have created a draft PR: https://github.com/liftbridge-io/liftbridge-cli/pull/1

There is still some work to do if we want to expose all the API, but this could be a first step. All comments are welcome.
