### ISSUE TITLE
Encapsulate the NATS protocol with GRPC

### ISSUE THREAD

**Issue by gedw99** [liftbridge-io/liftbridge#25]
The intent is to not expose the NATS import to the clients.
This means that we are building a NATS proxy and exposing it over GRPC to the Clients.

The payoff is that any language that can use GPRC ( many ) can use NATS.

**Comment by tylertreat** [comment]
I think we should probably expose a publish endpoint. This would basically be a straight pass-through to NATS.

```
rpc Publish(PublishRequest) returns (PublishResponse) {}

message PublishRequest {
    Message message = 1; // structured message
    bytes rawMessage = 2; // raw payload if not using structured
}
```

There are a couple nuances to think about though:

- If performance is important, this probably needs to be a "streaming" API.
- This should be able to handle acks from Liftbridge. The trick here is if we support "async" publishes, the server would need to track some state for each client with respect to in-flight messages. Might not be a huge deal, but something to be aware of.

**Comment by gedw99** [comment]
yeah that makes sense.
On the subscribe side also the same - MUST ACK.
As part as tracking of both PUB and SUB calls we can call it a "CorrelationID" maybe. THat naming is oftne used for Lng Running business Transaction though, SO maybe call it "BusCorrelaionID"

Anyway, super exciting stuff.   

Some background about amazing stuff that can be done with this.
I often write the servers in Golang and the Clients in Dart (Angular Dart and Flutter Dart). I have had no real issues doing this. Now Dart GRPC-web is almost done too.
SO, you can use Liftbridge for Microservices, but also for Clients.  So this means you can build systems where the NATS Router / Proxy is ( behind a normal reverse proxy of course) receives the calls from the Clients and routes the messages to the Microservices. The opposite is also true or real time updates to the Clients too, in that a Microservice can change its state for a Data Row ( or grpc object) and an event can be sent out across the NATS proxy and up to the Client. This event would be a CRUD event saying what changed. The client gets is and applies it to the Clients data. 

Now building quite complex systems becomes much easier to reason about. 

This is just one use case of how amazing NATS with GRPC is, and how much standing on the shoulders of giants it offers. 

References:

https://github.com/grpc/grpc-dart
https://github.com/grpc/grpc-dart/pull/109

**Comment by gedw99** [comment]
that makes sense having read your view on it.

There is a GRPC wrapper. Its called xbus and used in Prod.
https://orus.io/post/nats-xbus-and-tls/
https://bitbucket.org/orus-io/xbus/src/default/

Not being pushy but its nice to review others work etc.

**Comment by tylertreat** [comment]
Closing this for now. As discussed above, the intention will not be to encapsulate the full NATS protocol within Liftbridge but to eventually expose a publish gRPC API and implement a "standalone" mode for Liftbridge.

**Comment by gedw99** [comment]
Ok the final conclusion works for my use cases. Thanks again !
