### ISSUE TITLE
min.insync.replicas for StreamOptions request

### ISSUE THREAD

**Issue by riaan53** [liftbridge-io/liftbridge#269]
Hi, I have different requirements per stream and would like to configure `min.insync.replicas` when creating a stream as a `StreamOptions`. Can it be done in possible future work or is this an underlying limitation?

**Comment by tylertreat** [comment]
Yes, this can be done and I think is a good enhancement. Will take a look...

**Comment by tylertreat** [comment]
This has been merged in https://github.com/liftbridge-io/liftbridge/pull/270 and will be included in the next release. Support for the Go v2 client was also merged in https://github.com/liftbridge-io/go-liftbridge/pull/86.

**Comment by riaan53** [comment]
That was quick! Thanks for this awesome project :)
