### ISSUE TITLE
panic when starting multiple servers concurrently

### ISSUE THREAD

**Issue by lmars** [liftbridge-io/liftbridge#283]
We at [Ably](https://www.ably.io) have been testing our Liftbridge integration and have been experiencing the following panic when starting multiple servers concurrently:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a0dc09]

goroutine 331 [running]:
github.com/liftbridge-io/liftbridge/server.(*activityManager).createActivityStream(0xc0005be640, 0x0, 0xc0006f6028)
        /Users/lewis/go/pkg/mod/github.com/liftbridge-io/liftbridge@v1.3.0/server/activity.go:210 +0x179
```

Looking at the code, this panic suggests that the server's loopback client is not yet created when it's promoted to a leader, and it tries to use a `nil` client to create an activity stream [here](https://github.com/liftbridge-io/liftbridge/blob/v1.3.0/server/activity.go#L210).

I was able to reproduce this using the following test case (although the panic is intermittent):

```go
// Ensure servers with activity stream enabled can be bootstrapped concurrently
func TestBootstrapConcurrentWithActivityStream(t *testing.T) {
	defer cleanupStorage(t)

	// Use a central NATS server.
	ns := natsdTest.RunDefaultServer()
	defer ns.Shutdown()

	// Start three servers concurrently with activity stream enabled
	ids := []string{"s1", "s2", "s3"}
	type result struct {
		server *Server
		err    error
	}
	results := make(chan *result, 3)
	done := make(chan struct{})
	defer close(done)
	for _, id := range ids {
		go func(id string) {
			config := getTestConfig(id, false, 0)
			config.Clustering.ServerID = id
			config.Clustering.RaftBootstrapPeers = ids
			config.ActivityStream.Enabled = true

			server, err := RunServerWithConfig(config)

			select {
			case results <- &result{server, err}:
			case <-done:
			}
		}(id)
	}

	// wait for the servers to start
	for i := 0; i < 3; i++ {
		res := <-results
		if res.err != nil {
			t.Error(res.err)
		} else {
			defer res.server.Stop()
		}
	}
}
```

Here's a good test run:

```
$ go test -v --run TestBootstrapConcurrentWithActivityStream -count=1 ./server
=== RUN   TestBootstrapConcurrentWithActivityStream
--- PASS: TestBootstrapConcurrentWithActivityStream (5.26s)
PASS
ok      github.com/liftbridge-io/liftbridge/server      5.287s
```

and here's a bad one:

```
$ go test -v --run TestBootstrapConcurrentWithActivityStream -count=1 ./server
=== RUN   TestBootstrapConcurrentWithActivityStream
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1982389]

goroutine 153 [running]:
github.com/liftbridge-io/liftbridge/server.(*activityManager).createActivityStream(0xc000130ec0, 0x0, 0xc0001685a8)
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/activity.go:210 +0x179
github.com/liftbridge-io/liftbridge/server.(*activityManager).BecomeLeader(0xc000130ec0, 0xc000122240, 0x2a)
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/activity.go:72 +0x44
github.com/liftbridge-io/liftbridge/server.(*Server).leadershipAcquired(0xc0003b4000, 0xc0004c3f08, 0x2)
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/server.go:595 +0x1e4
github.com/liftbridge-io/liftbridge/server.(*Server).startMetadataRaft.func1()
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/server.go:533 +0x1ba
github.com/liftbridge-io/liftbridge/server.(*Server).startGoroutine.func1(0xc0001a1640, 0xc0003b4000)
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/server.go:958 +0x27
created by github.com/liftbridge-io/liftbridge/server.(*Server).startGoroutine
        /Users/lewis/src/github.com/liftbridge-io/liftbridge/server/server.go:957 +0x97
FAIL    github.com/liftbridge-io/liftbridge/server      1.505s
FAIL
```

I _think_ the issue is that as part of initialising a loopback client, the server broadcasts a message to gather info from the other peers and waits for them all to respond [here](https://github.com/liftbridge-io/liftbridge/blob/v1.3.0/server/metadata.go#L231-L256), which for `s1` likely blocks as the other servers were not yet listening for that request, but then if `s1` gets promoted to a leader, it performs its leader duties even though its loopback client request is still blocked.

Perhaps there needs to be synchronisation between setting the loopback client and creating the activity stream.

**Comment by tylertreat** [comment]
Thanks for the detailed bug report. That is indeed an unfortunate race condition. I'll take a look.

**Comment by tylertreat** [comment]
@lmars If you're able to, could you please try this branch to see if it resolves your issue? https://github.com/liftbridge-io/liftbridge/tree/fix_loopback_client_race

**Comment by lmars** [comment]
@tylertreat it does solve the panic yes, although it does now introduce a 5s delay when starting the server, which I assume is due to [this timeout](https://github.com/liftbridge-io/liftbridge/blob/v1.3.0/server/metadata.go#L219-L221) making the API server give up on fetching the metadata from all the peers during the course of connecting a client? If that's the case, perhaps this loopback client could somehow skip that, since I'm guessing it doesn't need information about other servers in the cluster?

**Comment by tylertreat** [comment]
Yep, will address the timeout issue.

**Comment by tylertreat** [comment]
@lmars I believe I've addressed the issue. Could you try pulling the latest version of that branch to see how it works for you?

I ended up replacing the loopback client with direct API calls, bypassing the network/gRPC entirely, which feels more appropriate anyway.

**Comment by lmars** [comment]
@tylertreat yes that works well, thanks!
