### ISSUE TITLE
Debezium/Kafka replacement for PostgreSQL to Elasticsearch or MeiliSearch sync?

### ISSUE THREAD

**Issue by rrjanbiah** [liftbridge-io/liftbridge#293]
Apologies for posting question here.

I'm looking to replace JVM for PostgreSQL to Elasticsearch and PostgreSQL to MeiliSearch incremental sync. Is this possible and has anyone implemented it? TIA

**Comment by tylertreat** [comment]
I don't think this is the appropriate place to post this issue since I'm not sure how it relates to Liftbridge.
