### ISSUE TITLE
too many deleted index file mmap after cleaning log

### ISSUE THREAD

**Issue by hl3w22bupt** [liftbridge-io/liftbridge#302]
![image](https://user-images.githubusercontent.com/3297112/102710576-1f513f00-42ee-11eb-95c7-8e2ea9d49f20.png)
When I publish massive message to liftbridge with nats-bench tool, the RES increase continuously.  And when time flies, I observed liftbridge print log "Cleaning log...." and there are increasing deleted index mmap segments when pmap the process

I also searched the source code, there is no gommap.Unmap call.  it seemed that the code only close and remove log file and index file. Also the munmap manually page clearly states: `On the other hand, closing the file descriptor does not unmap the region`, so **will it cause memory leak without munmap**? 

My liftbridge is v1.3.0, go version is 1.15
Finally I really love liftbridge, pretty cool and lightweight

**Comment by tylertreat** [comment]
You may have found a bug. Looks like there is an unmap missing in `Close`.

**Comment by tylertreat** [comment]
This should now be fixed with #303. @hl3w22bupt Can you confirm this resolves your issue, then I will make a patch release.

**Comment by hl3w22bupt** [comment]
> This should now be fixed with #303. @hl3w22bupt Can you confirm this resolves your issue, then I will make a patch release.

Yes, solves my issue, thanks : )
