### ISSUE TITLE
Breaking replica sync in case of message more than 1Mb

### ISSUE THREAD

**Issue by ekbfh** [liftbridge-io/liftbridge#305]
Liftbridge 1.4.0
Cluster of 3 lb, 3 nats.
nats max_payload: 7Mb

min isr 2, send message with size bigger than 1Mb, than replica is going out from ISR sync cause of timeout.
`level=error msg="Replica stage-wrk2 for partition [subject=message, stream=message, partition=0] exceeded max lag time (last seen: 3.912205858s, last caught up: 15.000038642s), removing from ISR"`

Please, consider a possibility to move https://github.com/liftbridge-io/liftbridge/blob/d5214eb82cf79a235712ae2d07cffcb74ff010ec/server/replicator.go#L20 to settings and also maybe good to check message size on `Publish` action to prevent this situation

**Comment by tylertreat** [comment]
This has been addressed in #308. There is now a new configuration, `clustering.replication.max.bytes`.
