### ISSUE TITLE
Consumer Groups API Proposal

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#307]
This is an API proposal for consumer groups. The goal is to collect feedback and discussion from the community before implementing, so please offer any thoughts or ideas you might have.

## What/Why

Consumer groups is an API to better facilitate the consumption of Liftbridge streams. This encompasses several different but related goals:

1. Provide a mechanism for clients to track their position in a stream automatically, i.e.  "durable" consumers. This builds on [cursors](https://liftbridge.io/docs/cursors.html) such that cursor management is transparent to users.
2. Provide a mechanism for distributed, fault-tolerant stream consumption.
3. Provide a mechanism for coordinating and balancing stream consumption by managing partition assignments for consumers.
4. Provide a mechanism for consuming multiple streams in aggregate.

## Proposed API

Below are the proposed additions to the client API. Note that this does not yet directly map to Liftbridge's gRPC API as that will be backed out from the client API once determined. I've written this using the Go client API since this is considered the "canonical" API. This is just a summary of the proposed user-facing changes.

```go
// Create a consumer that is part of a consumer group which consumes a set of
// streams. Liftbridge handles assigning partitions to the group members and
// tracking the group's position in the streams.
CreateConsumer(groupID string, streams []string, opts ...ConsumerOption) (*Consumer, error)
```

`CreateConsumer` is an addition to the `Client` interface for creating/joining consumer groups. This takes an ID which uniquely identifies the group and a set of streams to consume. `ConsumerOptions` provides a way for configuring consumer behavior, such as how frequently to checkpoint consumer positions or disabling automatic checkpointing.

```go
// Begin consuming from assigned partitions. If no partitions are assigned to
// this consumer, this will wait for partitions to be assigned.
func (c *Consumer) Subscribe(ctx context.Context, handler Handler) error
```

`Subscribe` will lazily initialize the consumer by joining or creating the group and receiving messages from assigned partitions.

```go
// Checkpoint the consumer's stream positions. This is used when not relying on
// automatic checkpointing.
func (c *Consumer) Checkpoint(ctx context.Context) error
```

`Checkpoint` provides a way to manually update the consumer's cursors. Normally this is done automatically in `Subscribe`, but this allows the user to control exactly when and how checkpointing occurs.

### Durable Consumer Example

Below is an example of a durable consumer, i.e. a consumer whose position in a stream partition is automatically managed by Liftbridge. Cursors are checkpointed in the background and the frequency in which they are checkpointed can be configured using `ConsumerOptions` based on requirements around performance and redelivery.

```go
addrs := []string{"localhost:9292", "localhost:9293", "localhost:9294"}
client, _ := lift.Connect(addrs)

stream := "foo" // Name of stream with 1 partition
consumerGroupID := "my-consumer" // Unique group name

// Create a consumer which will consume a single stream which has a single
// partition. This creates a consumer group, called "my-consumer", which has a
// single member.
consumer, _ := client.CreateConsumer(consumerGroupID, []string{stream})

// Begin consuming the stream. At this point, Subscribe will begin reading from
// wherever the consumer last left off.
consumer.Subscribe(context.Background(), func(msg *lift.Message, err error) {
    fmt.Println(msg.Offset(), string(msg.Value()))
})
```

### Multiple Streams Example

Here is an example of a consumer group consuming multiple partitioned streams. In this case, Liftbridge attempts to balance partitions amongst members of the group. If a member fails, its partitions will be reassigned.

```go
addrs := []string{"localhost:9292", "localhost:9293", "localhost:9294"}
client, _ := lift.Connect(addrs)

streams := []string{"foo", "bar", "baz"} // Streams to consume
consumerGroupID := "my-consumer-group" // Consumer group name

// Create a consumer which will be part of a group that will consume several
// streams.
consumer, _ := client.CreateConsumer(consumerGroupID, streams)

// Begin consuming. This will begin receiving messages for any partitions that
// have been assigned to this consumer. If no partitions are assigned, this will
// standby until partitions are assigned to it, such as in the event another
// consumer crashes.
consumer.Subscribe(context.Background(), func(msg *lift.Message, err error) {
    fmt.Println(msg.Stream(), msg.Partition(), msg.Offset(), string(msg.Value()))
})
```

### Minimizing Redeliveries Example

This example disables automatic cursor checkpointing and instead manually checkpoints the consumer's position after each message is processed. This allows the consumer to minimize the number of message redeliveries in the event of a failover.

```go
addrs := []string{"localhost:9292", "localhost:9293", "localhost:9294"}
client, _ := lift.Connect(addrs)

streams := []string{"foo", "bar", "baz"} // Streams to consume
consumerGroupID := "my-consumer-group" // Consumer group name

// Create a consumer which will be part of a group that will consume several
// streams. Disable automatic checkpointing.
consumer, _ := client.CreateConsumer(consumerGroupID, streams, lift.AutoCheckpoint(false))

// Checkpoint cursor after each processed message.
consumer.Subscribe(context.Background(), func(msg *lift.Message, err error) {
    fmt.Println(msg.Stream(), msg.Partition(), msg.Offset(), string(msg.Value()))
    consumer.Checkpoint(context.Background())
})
```

## Implementation Approach

The bulk of the work and complexity comes from group coordination, e.g. handling partition assignments, member failover, etc. However, single-member consumer groups still offer a lot of value without much of the coordination work, i.e. as a means for durable subscribers. Therefore, I believe the first step to implementing consumer groups should be limiting membership to 1 to provide value quicker and then generalizing to multi-member groups.

**Comment by annismckenzie** [comment]
This is awesome! I agree that to get value quicker the durable consumer use case with a single-member consumer group would be highly appreciated and a good plan to get started.

Thank you for the detailed write up, I always appreciate these. 🙂

Happy Holidays!

**Comment by riaan53** [comment]
Looks good! Something that google pubsub has is nack support (not just checkpointing) which controls redelivery. For example if the consumer does not what to process the message or busy shutting down it can just nack the message and it can be immediately redelivered to other consumers instead of waiting for the ack (checkpointing) timeouts. Also the automatic ack deadline extension for long message processing works great.

https://pkg.go.dev/cloud.google.com/go/pubsub#hdr-Deadlines

**Comment by tylertreat** [comment]
I'm not sure how nacking would work in the context of Liftbridge consumer groups or, more generally, in the case of a log rather than a queue with competing consumers. Since a consumer group only has 1 active consumer of a partition, what would happen if that consumer nacks a message? Would another standby consumer get selected to consume starting at the nacked message? Would we skip that message and continue delivering subsequent messages or block until the nacked message is consumed?

I think for acking/nacking to work, there would need to be entirely different consumer semantics introduced that would provide more queueing-like functionality on top of the log (similar to Apache Pulsar's different [subscription types](https://pulsar.apache.org/docs/en/concepts-messaging/#subscriptions)), which perhaps could extend consumer groups somehow.

**Comment by Huangsir** [comment]
Looks good! Is there any time plan for this proposal?

**Comment by tylertreat** [comment]
Goal is H1 2021 (see [roadmap](https://liftbridge.io/docs/roadmap.html#consumer-groups-46httpsgithubcomliftbridge-ioliftbridgeissues46).

**Comment by tylertreat** [comment]
This work is nearing completion. Follow https://github.com/liftbridge-io/liftbridge/issues/46 for updates.
