### ISSUE TITLE
Best GRPC Cli?

### ISSUE THREAD

**Issue by andyl** [liftbridge-io/liftbridge#31]
I tried `grpc_cli` to query from a liftbridge server and it failed.  (`grpc_cli ls localhost:9292`)

Does anyone know a GRPC client that works with liftbridge?

ps does liftbridge support "grpc reflection"?  (I think that is required by `grpc_cli`...)

**Comment by tylertreat** [comment]
Right now the Go client is the only client, or you can use the grpc
protobufs to build your own. But can you describe why it didn't work?

**Comment by tylertreat** [comment]
Maybe I misunderstood the question. There is no CLI available for
Liftbridge currently. I'm not familiar with the tool you tried.

**Comment by andyl** [comment]
OK thanks for the feedback.  Never used GRPC so I have a bit of a learning curve.  I'll try to get a GRPC/Ruby client working.
