### ISSUE TITLE
Is there any way to enable stream cursors?

### ISSUE THREAD

**Issue by strahe** [liftbridge-io/liftbridge#316]
I found: https://liftbridge.io/docs/configuration.html#cursors-configuration-settings

"A value of 0 disables the cursors stream. This cannot be changed once it is set."

So， is there any way to reconfigure an existing cluster？

**Comment by tylertreat** [comment]
You need to set `cursors.stream.partitions` to something greater than zero in the config file and restart each node in the cluster.

**Comment by strahe** [comment]
Thanks
