### ISSUE TITLE
Liftbridge can't start if some of nats servers is down

### ISSUE THREAD

**Issue by ekbfh** [liftbridge-io/liftbridge#328]
Hi!
I have 3 nodes, LB + nats-server on each node

```
nats.servers:
- nats://10.0.0.29:4222
- nats://10.0.0.30:4222
- nats://10.0.0.31:4222
```
Two of three nats-servers were working and was online, only one was down (on nats://10.0.0.31:4222). 
```
INFO[2021-02-14 15:56:12] Liftbridge Version:        v1.5.0            
INFO[2021-02-14 15:56:12] Server ID:                 *event04      
INFO[2021-02-14 15:56:12] Namespace:                 liftbridge-default 
INFO[2021-02-14 15:56:12] NATS Servers:              [nats://10.0.0.29:4222, nats://10.0.0.30:4222, nats://10.0.0.31:4222] 
INFO[2021-02-14 15:56:12] Default Retention Policy:  [Age: 1 day, Compact: false] 
INFO[2021-02-14 15:56:12] Default Partition Pausing: disabled          
INFO[2021-02-14 15:56:12] Shutting down...                             
WARN[2021-02-14 15:56:12] Attempted to access Raft node but it was not initialized 
panic: failed to connect to NATS: nats: no servers available for connection

goroutine 1 [running]:
main.main()
	/home/circleci/project/main.go:25 +0x1bc
```
Is it bug or feature?

**Comment by ekbfh** [comment]
Sorry, was my fault. All nats-servers were down at the moment of third LB was starting.

But it was very strange cause none of two LBs weren't failing while third can't start
Am i right, that even one of several nats servers in config is enough for working LB cluster?

**Comment by tylertreat** [comment]
Yes, as long as all of the NATS servers are provided to the Liftbridge config, it should work as long as at least 1 NATS server is up.

Is it possible the NATS servers were running at the time the other Liftbridge servers were started? Liftbridge will attempt to reconnect to NATS and will log messages when it is disconnected and reconnected to NATS.

**Comment by ekbfh** [comment]
Thanks for clarification. 

Yes, it's possible. I have plan to migrate to internal nats server after possibility to gather some metrics about it.
