### ISSUE TITLE
Provide access to Raft's log

### ISSUE THREAD

**Issue by Jmgr** [liftbridge-io/liftbridge#335]
Would it be possible to add some sort of callback/listener to Liftbridge's `Server`? We are embedding it into our own process and would like to be notified when there has been a partition leader change, for example. This process' behavior would then change depending on that.

**Comment by tylertreat** [comment]
Where do you see exposing a listener, somewhere in the FSM `Apply`?

**Comment by Jmgr** [comment]
I could see a new `AddRaftLogListener` function (or similar) added to the [Server](https://github.com/liftbridge-io/liftbridge/blob/b9884972b95783a626f7cf077705f75c1d4482a2/server/server.go#L47) and the listeners called in [Apply](https://github.com/liftbridge-io/liftbridge/blob/b9884972b95783a626f7cf077705f75c1d4482a2/server/fsm.go#L55), yes.

**Comment by tylertreat** [comment]
I think that makes sense. I envision that being called around [here](https://github.com/liftbridge-io/liftbridge/blob/b9884972b95783a626f7cf077705f75c1d4482a2/server/fsm.go#L113). I would prefer to avoid leaking the Raft implementation to the API, so I think we would either want to wrap the Hashicorp Raft [Log](https://pkg.go.dev/github.com/hashicorp/raft#Log) struct or pass the relevant primitive fields into the listener. A struct seems more extensible/flexible though.
