### ISSUE TITLE
Priority per topic/message

### ISSUE THREAD

**Issue by supapo** [liftbridge-io/liftbridge#359]
Does Liftbridge support priority between topics (even on the consumer side) or per messages?

**Comment by tylertreat** [comment]
I'm not sure how prioritization would work with Liftbridge given topics are ordered, durable message logs. Can you explain what you mean by that?

**Comment by supapo** [comment]
My use case is a chatbot that supports multiple platforms. The logic of the bot is on one process and the chat drivers on another.
Sometimes we send automatic messages, and sometimes we replay to user's messages. Therefore we need to answer first to the replay users and delay the replay for the auto-messages
I thought to implement this with priority like it this [thread](https://stackoverflow.com/questions/30655361/does-kafka-support-priority-for-topic-or-message). 

Thank you @tylertreat

**Comment by tylertreat** [comment]
As you can see from the Stackoverflow question you linked, Kafka also does not support this functionality for similar reasons (Kafka and Liftbridge are similar in design and intended use cases).

As that answer suggests, what you would do is create separate streams for different priorities and ensure messages from the high priority stream are processed first in your code.

**Comment by supapo** [comment]
OK, thank you @tylertreat
