### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by hamidrezakks** [liftbridge-io/liftbridge#361]
Hi,

Thanks for the great project,
Is this project actively under development? (I was following your published roadmap and it seem it's not on the track) 
Can I use it in a production environments?

**Comment by LaPetiteSouris** [comment]
Hi

I only contributed to some small parts of the roadmap, so my point of view may be incomplete:

- Most of important features have been implemented . Without knowing your specific use cases, we cannot say that the features you wish have been implemented or not. But IMHO, most of the base use cases are covered. You may refer to [Feature Matrix](https://liftbridge.io/docs/feature-comparison.html) to decide.

- The implemented features are tested, to my limited knowledge, it seems that there are other people who deployed in for production usage. I used Liftbridge myselft in a production environment in H1 2020. Again, it depends on your use cases.

- The project is very active. Bugs/Issues are processed in a very reactive way. For the Roadmap, I suppose  it is rather ambitious (as any roadmap), so there may be delays. At least, me, as an individual contributor, always try my best to find time for contribution.

**Comment by hamidrezakks** [comment]
Hi,
Thank you for the reply!
So can I use it as an alternative to the rabbitMQ?

**Comment by danthegoodman1** [comment]
@hamidrezakks I would keep in mind the differences between Queues and Streaming, so I would only do so if your use case allows those 2 to be interchangeable

**Comment by tylertreat** [comment]
Yes, this project is in active development and has a stable API. The current priority is focused on delivering consumer group functionality. The published roadmap is intended to provide visibility into the _direction_ and vision of the project and is not a firm commitment to deadlines. I will probably update it to reflect this more clearly.
