### ISSUE TITLE
Auth/AZ questions with NATS interoperability

### ISSUE THREAD

**Issue by hobti01** [liftbridge-io/liftbridge#37]
First of all, I really like what you've done here.  As I look more closely I'd like to have a good understanding of some details.  I didn't want to hijack the other issue so I've opened this one for my questions.

> Unlike NATS Streaming, it uses the core NATS protocol with optional extensions. This means it can be added to an existing NATS deployment to provide message durability with no code changes.

If authentication and authorization are not using NATS auth/az - how does this mean no code changes?

On first read of your blog post and other information, it seems like liftbridge is the solution that nats-streaming should (wanted to?) be.  I'm trying to find a good streaming solution, nats looks great, but it seems that the two simply are not fitting.

As I look at NATS-Streaming more closely I don't see authorization for streaming clients there either - can you help me understand what the options are to authorize connections based on your past interaction with the NATS streaming project and current efforts on liftbridge?

Finally, if it's just easier to point me to a tutorial or example, that's OK too :)

**Comment by tylertreat** [comment]
> If authentication and authorization are not using NATS auth/az - how does this mean no code changes?

This is unrelated to authn/authz. It is "no code change" in the sense that a Liftbridge server can be started and will begin recording messages from NATS to a durable stream without any code changes from the publisher's perspective. With NATS Streaming, it's an entirely different protocol and requires *replacing* NATS code with NATS Streaming code.

> it seems like liftbridge is the solution that nats-streaming should (wanted to?) be.

IMO yes, which is why I built it. :)

> As I look at NATS-Streaming more closely I don't see authorization for streaming clients there either - can you help me understand what the options are to authorize connections based on your past interaction with the NATS streaming project and current efforts on liftbridge?

Both NATS Streaming and Liftbridge do not address this currently. I can't speak to the NATS Streaming roadmap or what their plans are for this, but I intend to eventually provide a solution in Liftbridge. This will probably work in a similar fashion to what NATS (gnatsd) does.

**Comment by hobti01** [comment]
Thanks for the candid feedback :)  Your solution looks super interesting.  Does your roadmap list what you deem necessary to be production ready?

RE Auth/Az, do liftbridge and "liftbridge clients" both have the option to authenticate to the NATS server (gnatsd)?  I don't see any examples that use a `nats://` url with username/password

**Comment by tylertreat** [comment]
> Does your roadmap list what you deem necessary to be production ready?

I think from a feature perspective, it's there. I would like to do a bit more chaos testing to make sure there aren't data consistency or other weird issues.

> RE Auth/Az, do liftbridge and "liftbridge clients" both have the option to authenticate to the NATS server (gnatsd)? I don't see any examples that use a nats:// url with username/password

Liftbridge architecture is this:

```
publishers --> gnatsd --> Liftbridge --> subscribers
```

So on the publish side, gnatsd authn/authz works as is. What's missing is authn/authz on the subscribe side in Liftbridge.

As a side note, the vision is to eventually allow Liftbridge to run as a "standalone" system by implementing an embedded NATS mode, so it would look something like this:

```
publishers --> Liftbridge --> subscribers
```

In this case, gnatsd would sort of become an implementation detail (though could still be exposed for vanilla NATS clients if needed).

**Comment by hobti01** [comment]
Thanks for the information!

**Comment by gedw99** [comment]
I wonder if the "keys" repo over at NATS repo might also be incorporated eventually.
From what I can see if makes NATS encrypted over the wire ?
