### ISSUE TITLE
Alter Replication Protocol to use Leader Epoch rather than High Watermark for Truncation

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#38]
Currently, when a replica starts, it truncates its log up to the high watermark (HW) to remove any potentially uncommitted messages. There are a couple edge cases with this method of truncating the log that could result in data loss or replica divergence.

These can be solved by using a leader epoch rather than the high watermark for truncation. This solution was implemented in Kafka and is described [here](https://cwiki.apache.org/confluence/x/oQQIB). Liftbridge already implements a leader epoch, so this should be fairly straightforward to change.

**Comment by gedw99** [comment]
Is this different to what consul and Jocko do with raft and having to get a response from 51% of the nodes ?

**Comment by tylertreat** [comment]
Raft is not actually involved in *message* data replication, it's used for cluster metadata replication and leader election. Liftbridge uses a message data replication protocol very similar to Kafka. In fact, it's the same protocol up to more recent versions where this particular change was made, so this is just about bringing the protocol to parity.
