### ISSUE TITLE
Will liftbridge server be available for Windows 

### ISSUE THREAD

**Issue by matt-farmer** [liftbridge-io/liftbridge#43]
Currently we're building & running liftbridge with great success on Mac & Linux (wild-card subscriptions are a huge win!)

Attempted a golang cross-compile from Mac with GOOS=windows, with both go11 and go10 (there are changes to the syscall package in go11, thought that might be the cause, but same issue when reverting to go10).

to reproduce:

cd liftbridge-io/liftbridge
GOOS=windows GOARCH=amd64 go build

github.com/liftbridge-io/liftbridge/vendor/github.com/tysontate/gommap
vendor/github.com/tysontate/gommap/gommap.go:52:12: undefined: syscall.Stat_t
vendor/github.com/tysontate/gommap/gommap.go:53:13: undefined: syscall.Fstat
vendor/github.com/tysontate/gommap/gommap.go:58:15: undefined: mmap_syscall
vendor/github.com/tysontate/gommap/gommap.go:77:30: not enough arguments in call to syscall.Syscall

looking through the gommap source (perhaps unsurprisingly) there's no explicit support for architectures other than linux/mac.

Not  a huge issue for us for now, but is the intention to have a version of liftbridge that will work on windows in the future?

Once we get current release out the way happy to take a look at gommap in more detail to see if this is possible to extend or replace.

Thanks again for the hard work on the project, everything else is working very well of us.

**Comment by gedw99** [comment]
i tried to raise an issue at https://github.com/tysonmote/gommap/issues, but github is flakey today for me.
Really weird !!

**Comment by matt-farmer** [comment]
Thanks, that repo has been quiet for a while so if nothing comes of it we'll put a PR together for the gommap repo, but won't be for another 3 weeks or so until we can get the time to look into it in detail.

**Comment by matt-farmer** [comment]
Just for anyone following this we now have a working build for windows, and have created a patch to the original library so no code changes for liftbridge. We're still testing before we release a PR but it looks promising so hope to have details posted by the end of this week.

**Comment by matt-farmer** [comment]
Wow, how much does work that stops you doing work suck! Apologies for the longer delay than expected, but PR now submitted to the upstream repo https://github.com/tysonmote/gommap.

The map 'api' remains the same, so no changes required for liftbridge, and we've tested the lib heavily as part of liftbridge with no issues on windows.

There is a trivial code-fixup required in the liftbridge source so that anyone can build the server on windows:
‘liftbridge/server/signal_windows.go’,  ‘(s *StanServer)’ should be changed to ‘(s *Server)’ 
after that liftbridge will build and run on windows.

If the upstream original repo isn't able to accept our changes, then our fork is available at:
https://github.com/nsip/gommap
and we will be maintaining it, so dependencies in liftbridge could be updated to use the fork as an alternative. 

Want to be clear we leaned on others for prior art here, so full list of packages we investigated are listed on the fork readme and may be useful to anyone else looking for a golang mem-map for windows.

**Comment by tylertreat** [comment]
@matt-farmer Awesome, thank you! If the upstream mmap repo does not merge the changes, I'm happy to change Liftbridge to use the forked version. I'm not sure how actively maintained that repo is.

**Comment by tylertreat** [comment]
And thanks for pointing out the Windows build error. I've made a quick fix here: https://github.com/liftbridge-io/liftbridge/pull/47

**Comment by tylertreat** [comment]
@matt-farmer I've made a PR to the gommap fork in order to make it work with dep, which Liftbridge is still using for dependency management: https://github.com/nsip/gommap/pull/4

**Comment by tylertreat** [comment]
Addressed with #49. Let me know if there are any issues.
