### ISSUE TITLE
Visibility of messages between Liftbridge and NATS

### ISSUE THREAD

**Issue by hobti01** [liftbridge-io/liftbridge#45]
The README does a great job describing how Liftbridge is not NATS Streaming:
> NATS Streaming provides a similar log-based messaging solution. However, it is an entirely separate protocol built on top of NATS. NATS is simply the transport for NATS Streaming. This means there is no "cross-talk" between messages published to NATS and messages published to NATS Streaming.

But in the next paragraph I'm missing a key insight: Does Liftbridge allow "cross-talk"?  Are messages I publish with the Liftbridge client visible to a "standard" NATS client?  Can a NATS client subscribe to the same channels and see both "standard" and "liftbridge" messages?
> Liftbridge was built to augment NATS with durability rather than providing a completely separate system. NATS Streaming also provides a broader set of features such as durable subscriptions, queue groups, pluggable storage backends, and multiple fault-tolerance modes. Liftbridge aims to have a small API surface area.

**Comment by tylertreat** [comment]
You can't publish messages via Liftbridge currently as there is no publish
API. It's all through NATS. However, the plan is to add a publish API that
simply proxies messages to NATS.

**Comment by hobti01** [comment]
OK, clearer after looking at the [client library](https://github.com/liftbridge-io/go-liftbridge#publishing).  So NATS clients publish "as normal" and Liftbridge is (transparently) keeping the message log which Liftbridge clients can then request - is that an acceptable way to view things?

Does this mean that "non-liftbridge-enabled" clients will see the []byte message but not the metadata?

So persistence is truly "opt-in" where:
* publishers that send metadata can get acks for delivery guarantee to liftbridge
* published messages without metadata are still persisted (but not guaranteed?)
* clients can use pub/sub (without liftbridge)
* clients can subscribe to the stream (with liftbridge) for queue/stream operations

Apologies to repeat what you've documented, but I want to ensure that I have an understanding of what to expect regarding interoperability with NATS and the ability to only use persistence when needed.

Really great stuff, thanks for your impressive work!

**Comment by hobti01** [comment]
Thanks for the info!
