### ISSUE TITLE
Message delivery guarantee

### ISSUE THREAD

**Issue by mfcochauxlaberge** [liftbridge-io/liftbridge#58]
I have compiled and tried liftbridge on top of a cluster of NATS servers. It worked well. In order to send append a message to be appended to a log managed by liftbridge, I had to send the message to one of the NATS server.

I'm probably missing something, but how is message delivery guaranteed*? As far as I can tell, the guarantee offered by NATS is _at-most-once_.

https://nats.io/documentation/faq/#gmd (more about NATS delivery guarantees)

*If liftbridge is trying to achieve that.

**Comment by wallyqs** [comment]
I think you can create an special envelope when publishing the message that includes an ack inbox subject that can be used to correlate the messages that were published with their acks, check out: https://github.com/liftbridge-io/go-liftbridge#publishing

**Comment by mfcochauxlaberge** [comment]
Aaaah. How did I miss that. Thanks!
