### ISSUE TITLE
Publish official Docker image

### ISSUE THREAD

**Issue by sslavic** [liftbridge-io/liftbridge#6]
Please include Dockerfile and have official Docker image published nightly and with every release.

**Comment by tylertreat** [comment]
Docker images are [now available](https://hub.docker.com/repository/docker/liftbridge/liftbridge). Still planning to implement nightly/release-based tags so will leave this issue open to track that work.

**Comment by tylertreat** [comment]
We now build [standalone-dev](https://hub.docker.com/repository/docker/liftbridge/standalone-dev) images on every master build and release which are tagged with the commit hash or release tag as well as official [release](https://hub.docker.com/repository/docker/liftbridge/liftbridge) images on every tagged release.
