### ISSUE TITLE
Production ready.

### ISSUE THREAD

**Issue by supapo** [liftbridge-io/liftbridge#61]
Hi,
This project looks awesome. 
Do you know when it going to be production ready?

Thanks.

**Comment by tylertreat** [comment]
I don't have a firm timeline yet but hoping to have a stable "1.0" API by the end of July, meaning no breaking changes for clients. There's a bit more stress/chaos testing I need to do before calling it "production ready", but hopefully by the end of summer or early fall (Sept/Oct timeframe).

**Comment by tsingson** [comment]
@tylertreat  thanks a lot.

i had trial in site for some time( 3 month )  , it's look like work fine.  
yet, we waiting for a stable API.

**Comment by tylertreat** [comment]
The API is very close to being stable. I don't expect any major changes.
Let me know if I can help.

**Comment by tsingson** [comment]
> The API is very close to being stable. I don't expect any major changes. Let me know if I can help.
> […](#)

cool, let's try in business field............

**Comment by sandeepone** [comment]
Thanks. Can we use in production? Just curious

**Comment by tylertreat** [comment]
I would wait til a stable release before using in production. Release should be happening pretty soon.

**Comment by sandeepone** [comment]
@tylertreat Thank you

**Comment by Gaboose** [comment]
Great stuff. Any news on when it can be considered production ready?

**Comment by LaPetiteSouris** [comment]
Just want to jump in here to ask for progress on this. Can anyone give some hints on the set up you guys have been using in Production environment ?

**Comment by Just4Ease** [comment]
Any update on this?

**Comment by tylertreat** [comment]
The API is now stable with a backwards compatibility commitment, and there are uses of Liftbridge in production.

**Comment by Just4Ease** [comment]
Sweet, thanks bruv. 

Time for me to blaze up without limits 🚀🚀🚀
Watchout for some good news on amazing products built with liftbridge as the underlying system.

I don't want to use pulsar, it's just expensive and heavy. 🚀🚀🚀
