### ISSUE TITLE
should create a branch for github.com/nats-io/nats-server/v2 and github.com/nats-io/nats.go

### ISSUE THREAD

**Issue by tsingson** [liftbridge-io/liftbridge#69]
I try a branch for github.com/nats-io/nats-server/v2 and github.com/nats-io/nats.go

it's looks work well.

and it's work with gnatsd 1.4.1, so great

so, should v create a branch for this?

**Comment by tylertreat** [comment]
Feel free to make a pull request that updates NATS dependencies.

**Comment by tsingson** [comment]
done
