### ISSUE TITLE
Revisit config format

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#71]
Consider moving away from NATS config format and flattening/simplifying config. Also ensure config names follow a pattern, e.g. `log.level` and `log.recovery` instead of `log.level` and `show.recovery.logs`.

**Comment by tylertreat** [comment]
I'm currently thinking to change the config file format to use TOML, but continue supporting the "legacy" format for some time and eventually deprecate it.

**Comment by annismckenzie** [comment]
In our company we've had a good experience with the `go-flags` package for env variables and flags as well as `viper` for reading from config files.

**Comment by tylertreat** [comment]
I'll take a look at Viper, though I'm nervous about supporting lots of different config formats like JSON, TOML, YAML, HCL, envfile and Java properties config files all at once since it could get confusing from a documentation perspective? Seems like one canonical format would be simpler.

**Comment by annismckenzie** [comment]
YAML or TOML would be best I think. 😅
