### ISSUE TITLE
some confusing about go.mod ( module split ) 

### ISSUE THREAD

**Issue by tsingson** [liftbridge-io/liftbridge#76]
in liftbidge go.mod

```
module github.com/liftbridge-io/liftbridge

go 1.12

require (
 ....
	github.com/liftbridge-io/go-liftbridge v0.0.0-20190703015712-9f8cb1ad3118
...
}
 
```

and , in go-liftbridge go.mod 
```
module github.com/liftbridge-io/go-liftbridge

go 1.12

require (
...
	github.com/liftbridge-io/liftbridge v0.0.0-20190703152401-d5d0fe2ef597
...
)
```

it's cross depend, so , a suggest:

server side:
just import  gRPC protobuffer define file from https://github.com/liftbridge-io/liftbridge-grpc  and  generate  a  pb.go for server gRPC 

in client side:   
the same way to just import proto file from https://github.com/liftbridge-io/liftbridge-grpc , and generate  pb.go client code for client in go / java /........ 

so,  in this way to broke the cross depend in server and go client,  and server / client should be release independent.

.

**Comment by tylertreat** [comment]
Liftbridge depends on go-liftbridge for unit testing purposes and vice versa. This should be ok though since both should be pinned to a specific version.

**Comment by tsingson** [comment]
> Liftbridge depends on go-liftbridge for unit testing purposes and vice versa. This should be ok though since both should be pinned to a specific version.

thanks for clarify.
