### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by dgzlopes** [liftbridge-io/liftbridge#90]
Today trying to install Liftbridge on a fresh Vagrant box, Ubuntu 16.04 LTS with `go version go1.12.7 linux/amd64`, I got the following error:

```
vagrant@ubuntu-xenial:~$ go get github.com/liftbridge-io/liftbridge
# github.com/liftbridge-io/nats-on-a-log
go/src/github.com/liftbridge-io/nats-on-a-log/nats_transport.go:373:53: cannot use logger (type *log.Logger) as type hclog.Logger in argument to raft.NewNetworkTransportWithLogger:
	*log.Logger does not implement hclog.Logger (missing Debug method)
go/src/github.com/liftbridge-io/nats-on-a-log/nats_transport.go:386:60: cannot use config.Logger (type hclog.Logger) as type *log.Logger in argument to createNATSTransport

```

**Comment by tylertreat** [comment]
Do you have go modules enabled? I.e. `export GO111MODULE=on`

We recently switched to modules and I noticed it's not covered in the README yet.

**Comment by dgzlopes** [comment]
Oh! Thanks for the quick response. I didn't have the go modules enabled. Now all seems to work properly.

**Comment by tylertreat** [comment]
Cool, apologies for the poor documentation. Will get that updated shortly.

**Comment by tylertreat** [comment]
Added a note on Go modules to the install instructions, so closing this.
