### ISSUE TITLE
Webhook extension

### ISSUE THREAD

**Issue by supapo** [liftbridge-io/liftbridge#92]
Hi all,
I want to discuss about a Webhook extension. 

The main idea is to add a Webhook gateway feature to liftbridge.
Pub/sub software clients registered to some subject and listening to the messages.
How we can extend the regular behavior, and send the messages with an HTTP request.
Let's say that on the registration the client will declare a URL to send the messages in a known format.

What do you think about the approach? and how the design should look like?

**Comment by tylertreat** [comment]
My thought is this functionality would more belong in a separate "push gateway" server that sets up subscriptions for configured subjects and pushes to configured webhook URLs, rather than putting it in the server itself.

**Comment by tylertreat** [comment]
Closing this as there aren't plans to implement webhooks directly in Liftbridge. A separate webhook service as described above would be a great solution if someone is looking for a way to contribute.
