### ISSUE TITLE
Liftbridge Docker image embedding NATS

### ISSUE THREAD

**Issue by dgzlopes** [liftbridge-io/liftbridge#95]
Built a small Docker image [[0](https://github.com/dgzlopes/liftbridge-docker)] embedding NATS next to Liftbridge. I'm using it for the development of the Python client, and even if it's a little messy I think it's pretty useful for testing/dev purposes or having a quick Liftbridge experience.

During the next weeks, I'm going to add proper tagging and CD/CI so the Docker Hub image [[1](https://hub.docker.com/r/dgzlopes/liftbridge-docker)] is updated.

[0] https://github.com/dgzlopes/liftbridge-docker
[1] https://hub.docker.com/r/dgzlopes/liftbridge-docker

**Comment by tylertreat** [comment]
Thanks for the contribution! Happy to bring this under the liftbridge-io github org if you're interested. Up to you.

**Comment by dgzlopes** [comment]
Yeah, sure! I am happy to transfer it to the org.

Also, I think it might be interesting to change the container name to something less generic and maybe add the CI workflow on top of CircleCI... As Liftbridge main repo already uses it.

**Comment by tylertreat** [comment]
Moved [here](https://github.com/liftbridge-io/liftbridge/tree/master/docker/dev-standalone).
