### ISSUE TITLE
Maybe support Kafka abstraction ?

### ISSUE THREAD

**Issue by joeblew99** [liftbridge-io/liftbridge#96]
Saw this https://github.com/matrix-org/naffka/blob/master/naffka.go

Its a golang lib wrapping samara, but it got me thinking about the idea of allowing golang devs to easily try Kafka or Liftbridge via a unified API.

See here for Context:
https://github.com/matrix-org/dendrite/search?q=naffka&type=Issues

**Comment by joeblew99** [comment]
> Is your thought to support the Kafka protocol in the server or provide a high-level client that allows switching between Kafka and Liftbridge?

TO allow switching in a high level client.
So that lots of people using golang and kafka can easily switch.

> 
> Supporting the Kafka protocol would be really neat and would make adoption/migration really easy. My concern with that is there might be some impedance mismatch / leaky abstraction since, while conceptually similar, it's not an exact mapping and Kafka supports some features that Liftbridge doesn't currently.

I agree with your sentiments. I just wanted to raise it for looking at. When i saw the way they wrapped it in the Matrix Project a light bulb went off.
The lay of support of some Kafka specific things might be a problem, but i honestly don't have enough knowledge to give an informed answer. However Kafka is feature rich and so moving to LIftbridge i would think involves some compromise on their part naturally.

> 
> Providing a high-level wrapper that implements a lowest common denominator API between Liftbridge and Kafka would be easier. I think this is what you're suggesting?

YES. As per my comment above. Its always like this when you are supporting 2 engines. 

> 
> I also have plans to implement a Kafka bridge for Liftbridge, which would be a Kafka connector that maps topics in Kafka to streams in Liftbridge. This would allow Kafka users to start migrating to Liftbridge incrementally.

Thats a good idea too. There is a really nice golang project that does this already which i expect you know.  https://github.com/Jeffail/benthos

**Comment by joeblew99** [comment]
I agree about the impedance mismatch.
Yes a low level wrapper that does not support all the the Kafka functionality since yes there is an impedance mismatch.

For me my use case is CDC from Cockroach dB and Yugabtye.

https://github.com/yugabyte/yugabyte-db/issues/2513

 These and tidb are pretty common Google spanner like databases.
They all use avro schema and expect a Kafka system to be there to push / pull the CDC data to.

Of course there are probably 1000's of other systems that push to Kafka out there too for which liftbridge could offer a lifeline for where you don't want java.

**Comment by YourTechBud** [comment]
It would be super cool if Liftbridge could support the Kafka wire protocol. Adoption would become so much easier.

I understand there could be feature imparity initially, but the initial development efforts could be to bridge precisely that. Many like myself find Liftbridge as a Kafka alternative after all.

**Comment by tylertreat** [comment]
Closing this for now as there are currently no plans to support the Kafka protocol.
